

using Microlise.IntegrationTests.Sql;
using Microlise.IntegrationTests.Sql.GovernanceTests;
using Microlise.IntegrationTests.Sql.GovernanceTests.Filters;
using Microlise.IntegrationTests.Sql.Utilities;
using Template.Application;

namespace Template.Integration.Tests
{
    public class Tests
    {
        [SetUp]
        public void Setup()
        {
        }

        [Test]
        public void DoorStateEnumeration_MatchesDatabaseLookupTable()
        {
            EnumLookupValidation.AssertEnumMatchesDatabase<DoorState>("dbo.tbl_Session", "UserID", "userEmailAddress");
        }

        [Test]
        public void GovernanceTestSuite_Passes()
        {
            new GovernanceTestSuite()
                .FilterTest<DatabaseNameTest>(
                    new TestFilter()
                        .AddFilter("DeviceConfiguration.PreferenceSets", "My database name has a dot in it. So what!"))

                .FilterTest<UseDatetime2Test>(
                    new TestFilter()
                        .AddFilter( "archive.tbl_TrackedEvent.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "archive.tbl_TrackedEvent.processedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "archive.tbl_TrackedEvent.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "archive.tbl_TrackedEvent_Ecu.ChangeStatusDateInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "archive.tbl_TrackedEvent_Service.LastServicedDate", "Amber DATETIME legacy." )
                        .AddFilter( "archive.tbl_TrackedEvent_Speed.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "archive.tbl_TrackedEvent_Speed.processedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "archive.tbl_TrackedEvent_Speed.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "archive.tbl_TrackedEvent_Summary.lastServiceDate", "Amber DATETIME legacy." )
                        .AddFilter( "archive.tbl_TrackedEvent_Summary.LastServicedDateInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "archive.tbl_TrackedEvent_Summary.summaryStart", "Amber DATETIME legacy." )
                        .AddFilter( "archive.tbl_TrackedEvent_TMSData.EventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "archive.tbl_TrackedRawData.captureDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_Filter_GetVisibleVehicles.VehicleDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_GetEcoSafeScores_04.VehicleDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_GetMostRecentDriverDetailsForVehicle_01.Endtime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_GetMostRecentDriverDetailsForVehicle_01.StartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_GetStartAndEndTrackedEventValues.EndEventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_GetStartAndEndTrackedEventValues.StartEventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_GetUniqueVisibleVehicles.VehicleDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_GetVehicleOdometer.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_GetVisibleVehicles.VehicleDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_HealthData.EventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_HealthData.StartDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_SequentiallyNumberedSiteVisitsForAVehicle_02.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_SummaryTrackedEvent_GeneratorByVehiclesAndStartTime_01.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_SummaryTrackedEvent_GeneratorByVehiclesAndStartTime_01.lastServiceDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_SummaryTrackedEvent_GeneratorByVehiclesAndStartTime_01.LastServicedDateInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_SummaryTrackedEvent_GeneratorByVehiclesAndStartTime_01.processedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_SummaryTrackedEvent_GeneratorByVehiclesAndStartTime_01.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_SummaryTrackedEvent_GeneratorByVehiclesAndStartTime_01.summaryStart", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_SummaryTrackedEvents_01.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_SummaryTrackedEvents_01.lastServiceDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_SummaryTrackedEvents_01.LastServicedDateInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_SummaryTrackedEvents_01.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_SummaryTrackedEvents_01.summaryStart", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEvent_ElectricAllDataByVehiclesAndStartTime.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEvent_ElectricAllDataByVehiclesAndStartTime.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEvent_EngineStopStart_ByDateRange_VehicleId.EventDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEvent_PlantCanDataByVehiclesAndStartTime_01.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEvent_PlantCanDataByVehiclesAndStartTime_01.processedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEvent_PlantCanDataByVehiclesAndStartTime_01.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEventsByTrackedEventId.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEventsByTrackedEventId.processedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEventsByTrackedEventId.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEventsByTrackedEventIdRangeAndVehicleIds_01.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEventsByTrackedEventIdRangeAndVehicleIds_01.processedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEventsByTrackedEventIdRangeAndVehicleIds_01.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEventsByVehicleAndStartTime_01.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEventsByVehicleAndStartTime_01.processedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEventsByVehicleAndStartTime_01.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEventsByVehicleEventCodeAndStartTime.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEventsByVehicleEventCodeAndStartTime.processedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEventsByVehicleEventCodeAndStartTime.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_TrackedEventsTMSDataByVehicleAndStartTime.EventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.amberFunc_VehicleTenanciesBetweenDatesBelongingToTenant.AppliesToInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Account.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Account.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AGS_NightlyJobs.LastRunDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AISEmergencyEvents.LastEventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AISEmergencyEvents.StartEventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Attribute.createdDatetimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Attribute.lastModifiedDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AttributeCategory.createdDatetimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AttributeCategory.lastModifiedDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AttributeValues.createdDateTimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AttributeValues.lastModifiedDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Audit.datetime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AuditNavigation.DateTimeUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AuditReport.FromDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AuditReport.ReportEnd", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AuditReport.ReportStart", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AuditReport.ToDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AuditReport_old.FromDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AuditReport_old.ReportEnd", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AuditReport_old.ReportStart", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AuditReport_old.ToDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AuditReportError.ErrorTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_AuditReportError_old.ErrorTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_BillingContract.DateAutoRenewed", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_BillingContract.DateReportOnForInvoicing", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_BillingContract.EndDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_BillingContract.StartDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_BillingContractCancellations.CancellationDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_BillingContractCancellations.DateActioned", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_BillingContractRenewalCancellations.DateActioned", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_BillingContractRenewals.DateActioned", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_BusinessEvent.closedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_BusinessEvent.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_BusinessEvent.generatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_BusinessEvent.GeocodedDateTimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_BusinessEvent.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_CentralTrackingUnit.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_CentralTrackingUnit.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_CountRawDataMessages.processedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_CountTrackedEvents.processedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_D3GeofenceData.CreatedDateTimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_DashBoard_TotalVehiclesInCountry.LastTimeRan", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Driver.CreatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_DriverSession.LoggedOnDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_DriverVehicleDaySummary.EndTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_DriverVehicleDaySummary.FirstArrivalTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_DriverVehicleDaySummary.LastDepartureTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_DriverVehicleDaySummary.StartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_DriverVehicleDaySummary.VehicleDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_EcuFirmwareVersion.EventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_EngineRun.EndTimeUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_EngineRun.StartTimeUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_EngineRunDaySummary.FirstArrivalTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_EngineRunDaySummary.LastDepartureTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_EngineRunDaySummary.VehicleDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_EntityAttribute.createddatetimeinutc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_EntityImage.CreatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_EntityImage.LastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_EntityPerformanceTargets.createdDateTimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_EntityPerformanceTargetsSettings.createdDateTimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_ETL_DataImportLog.lastDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Group.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Group.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_GroupLocation.LocationGroupCreatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_GroupLocation.LocationGroupLastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_GroupType.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_GroupType.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_LocationGeofence.GeofenceCreatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_LocationGeofence.GeofenceLastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_LocationGeofenceOperatingTime.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_LocationGeofenceOperatingTime.endTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_LocationGeofenceOperatingTime.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_LocationGeofenceOperatingTime.startTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Locations.LocationCreatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Locations.LocationLastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_MasterProfileImport.ImportDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_MessageDestinations.ReadDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_MessageDestinations.ReceivedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Messages.CreatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Messages.SentDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_MobileAppVersions.LastUpdateDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_MobileSession.LastCallDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_OdometerAdjustment.ApplicableFromUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_OdometerAdjustment.CreatedDateTimeUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_OdometerAdjustment.UpdatedDateTimeUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_PerformanceTarget.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_PerformanceTarget.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_PowerWall_Current.LastContact", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_PowerWall_Current.MachineDown", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_PowerWall_Current.Uptime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_PowerWall_Daily.LastContact", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_PowerWall_Daily.MachineDown", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_PowerWall_Daily.Uptime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_PowerWall_Delta.LastContact", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_PowerWall_Delta.MachineDown", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_PowerWall_Delta.Uptime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_PowerWall_Latest.LastContact", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_PowerWall_Latest.MachineDown", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_PowerWall_Latest.Uptime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_RemoteDiagnosticsLogFile.LogDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_ResetEvent.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_ResetEvent.processedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_ResourceClaimsByUser.userClaimDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_ReverseGeocodeCache.CreatedDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_RoleIdentifierRole.CreatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_SafetyInspection.CompletedDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_SafetyInspection.DueDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Service.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Service.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Service_Old.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Service_Old.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_ServiceHistory.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_ServiceHistory.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_ServiceHistory.serviceDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Session.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Subscription.ExpiryDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Subscription.NextReportGenerationDateTimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Subscription.StartDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_SupportUI_Audit.datetime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_System.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_System.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TeaArchiveRunInformation.RunEndDateUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TeaArchiveRunInformation.RunStartDateUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TeaCopyRunInformation.RunEndDateUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TeaCopyRunInformation.RunStartDateUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Tenant.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Tenant.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Tenant_old.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Tenant_old.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TenantOperatingTime.EndTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TenantOperatingTime.StartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TenantVehicle.AppliesFromInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TenantVehicle.AppliesToInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TMLDSiteVisitMessage.EventDateTimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackedEvent.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackedEvent.processedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackedEvent.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackedEvent_Ecu.ChangeStatusDateInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackedEvent_Service.LastServicedDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackedEvent_Speed.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackedEvent_Speed.processedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackedEvent_Speed.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackedEvent_Summary.lastServiceDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackedEvent_Summary.LastServicedDateInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackedEvent_Summary.summaryStart", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackedEvent_TMSData.EventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackedRawData.captureDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnit.autoInactiveModeStartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnit.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnit.debugEndDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnit.lastCANDataDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnit.lastContactTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnit.lastEngineStartDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnit.lastEventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnit.lastGPSFixDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnit.lastResetEventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnit.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnit.lastVINDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnitCommandStatusUpdate.ReceivedDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnitCommunicationsToSystemsDetail.LastCommunicationDateTimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnitCompletedDownload.completedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnitCompletedDownload.generatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnitDownload.ExpiresOnInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnitDownload.generatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnitDownload.StatusDateInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnitFirmware.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnitFirmware.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnitLargeGenericData.ReceivedDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnitLargeGenericData.StartDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnitLog.generatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_TrackingUnitSecondaryModem.LastContactDateTimeUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_User.CreationDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_User.LastLoginDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_User.NightModeEndTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_User.NightModeStartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserAuthorisation.ActivationRequestDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserAuthorisation.CreationDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserAuthorisation.LastLoginDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserAuthorisation.SoftwareTermsLastAcceptedDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserAuthorisation.TermsLastAcceptedDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserCommunication.generatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserCommunication.statusDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserCommunicationProfile.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserCommunicationProfile.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserCommunicationsWebPushSubscription.CreatedDateTimeUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserCommunicationsWebPushSubscription.DeletedDateTimeUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserReportCriteriaAndSchedule.CreatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserReportCriteriaAndSchedule.ExpiryDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserReportCriteriaAndSchedule.FromDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserReportCriteriaAndSchedule.LastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserReportCriteriaAndSchedule.NextDueDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserReportCriteriaAndSchedule.StartDateAndTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_UserReportCriteriaAndSchedule.ToDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Vehicle.ActivateRemoteImmobiliserDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Vehicle.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Vehicle.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Vehicle.SafetyInspectionScheduleStartDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Vehicle.servicePeriodStartDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Vehicle.startOfDayTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Vehicle_Default_Driver_History.EndTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Vehicle_Default_Driver_History.StartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Vehicle_Driver.StartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Vehicle_Driver_History.EndTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Vehicle_Driver_History.StartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleActiveDTC.ActivatedTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleActivityHistory.fromEventDateTimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleActivityHistory.fromEventDateTimeInVehicleTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleActivityHistory.toEventDateTimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleActivityHistory.toEventDateTimeinVehicleTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleAttribute.createddatetimeinutc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary.activityEndTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary.activityStartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary.endDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary.firstEngineRun", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary.lastEngineRun", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary.LastServicedDateInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary.vehicleDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_AccessBoom.StartDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_Compact.StartDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_Compaction.StartDateTimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_CompactionStatus.StartDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_Customerwise_WeighloadData.StartDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_Earthmover.StartDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_Electric.StartDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_ElectricVehicles.StartDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_Generator.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_HeavyProduct.StartDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_HydrogenVehicles.StartDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_MotorData.StartDateTimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_Plant.StartDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_PowerPack.StartDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_RotoLoadall.StartDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_SkidSteer.StartDateTimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_WeighloadData.StartDateTimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDaySummary_WeighloadLiftData.StartDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDriverLocationSummary.EndTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDriverLocationSummary.StartTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDriverLocationSummary.VehicleDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDTCEvent.EventDateTimeUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDTCHistory.ActivatedTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleDTCHistory.ClearedTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleEngineOnSummary.PeriodStartTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleEngineOnSummary.PeriodStartTimeInVehicleTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleFSI.DateClosedInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleFSI.DateImportedInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleLocationGeofenceHistory.ArrivedTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleLocationGeofenceHistory.ArrivedTimeInGeoTimeZone", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleLocationGeofenceHistory.DepartureTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleLocationGeofenceHistory.DepartureTimeInGeoTimeZone", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleLocationGeofenceStatus.ArrivedTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleLocationGeofenceStatus.ProvisionalDepartureTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleMaxSpeedPeriodSummary.EventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleMovementSummary.fromEventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleMovementSummary.fromEventDateTimeInVehicleTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleMovementSummary.toEventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleMovementSummary.toEventDateTimeinVehicleTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleOperatingTime.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleOperatingTime.endTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleOperatingTime.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleOperatingTime.startTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehiclePINCodeCommandHistory.GeneratedDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehiclePINCodeCommandHistory.ProcessedDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleProfile.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleProfile.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleProfile.startOfDayTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleProfile.SupportsTotalLifeValuesSinceDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState.AdBlueInPoint4OfAPercentLastChanged", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState.currentDaySummaryStartDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState.engineRunPeriodStartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState.engineStateLastChanged", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState.excessiveIdleStartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState.FuelTimeRemainingIn10MinutesLastChanged", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState.idleStartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState.keyStateLastChanged", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState.lastEventTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState.lastGPSFixDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState.lastServiceDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState.OdometerLastChangedInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState.potentiallyStoppedEventTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState.SiteVisitedTimeInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState.stoppedStartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleState_TyrePressure.EventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleStateRemoteConfiguration.LastEventDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VehicleStateRemoteSocketConfiguration.LastEventDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_Viewstate.TimeStamp", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tbl_VTSTiming.ProcessedDateTimeInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tmp_MachineUtilisationDays.vehicledate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.tmp_MachineUtilisationHours.vehicleperiodstart", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_DriversCurrentlyDrivingVehicles.StartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_FleetUtilisationData.VehicleDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_NextGen_EngineRunDurations.StartDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_OdometerAdjustments.ApplicableFromUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_OdometerAdjustments.ApplicableToUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_QuickReport_NonReportingVehicles.LastEventTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_QuickReport_NonReportingVehicles.LastGPSFixDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_TenantVehicle_ForVehicleDaySummaryJoin.AppliesToInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleAcitivityDaySummary.activityEndTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleAcitivityDaySummary.activityStartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleAcitivityDaySummary.endDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleAcitivityDaySummary.firstEngineRun", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleAcitivityDaySummary.lastEngineRun", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleAcitivityDaySummary.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleAcitivityDaySummary.vehicleDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryRounded.activityEndTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryRounded.activityStartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryRounded.endDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryRounded.firstEngineRun", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryRounded.lastEngineRun", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryRounded.LastServicedDateInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryRounded.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryRounded.vehicleDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryWithDrivingTime.activityEndTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryWithDrivingTime.activityStartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryWithDrivingTime.endDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryWithDrivingTime.firstEngineRun", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryWithDrivingTime.lastEngineRun", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryWithDrivingTime.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryWithDrivingTime.vehicleDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryWithPercentages.activityEndTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryWithPercentages.activityStartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryWithPercentages.endDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryWithPercentages.firstEngineRun", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryWithPercentages.lastEngineRun", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryWithPercentages.startDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleDaySummaryWithPercentages.vehicleDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleMapObjects.activityEndTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleMapObjects.activityStartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleMapObjects.AppliesFromInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleMapObjects.AppliesToInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleMapObjects.engineStateLastChanged", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleMapObjects.fromEventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleMapObjects.keyStateLastChanged", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleMapObjects.LastEventTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleMapObjects.lastGPSFixDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleMapObjects.toEventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleProfile_UnsynchronisedDefaultProfiles.CreatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleProfile_UnsynchronisedDefaultProfiles.LastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleProfile_UnsynchronisedDefaultProfiles.StartOfDayTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehiclesCurrentlyBeingDrivenByDrivers.StartTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehiclesCurrentlyVisibleByUser.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehiclesCurrentlyVisibleByUser.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehiclesCurrentlyVisibleByUser.SafetyInspectionScheduleStartDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehiclesCurrentlyVisibleByUser.servicePeriodStartDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehiclesCurrentlyVisibleByUser.startOfDayTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesCurrentlyVisibleByTenancy.AppliesFromInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesCurrentlyVisibleByTenancy.AppliesToInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesCurrentlyVisibleByTenancy.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesCurrentlyVisibleByTenancy.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesCurrentlyVisibleByTenancy.SafetyInspectionScheduleStartDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesCurrentlyVisibleByTenancy.servicePeriodStartDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesCurrentlyVisibleByTenancy.startOfDayTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesCurrentlyVisibleByUser.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesCurrentlyVisibleByUser.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesCurrentlyVisibleByUser.SafetyInspectionScheduleStartDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesCurrentlyVisibleByUser.servicePeriodStartDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesCurrentlyVisibleByUser.startOfDayTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesVisibleByTenancy.AppliesFromInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesVisibleByTenancy.AppliesToInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesVisibleByTenancy.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesVisibleByTenancy.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesVisibleByTenancy.SafetyInspectionScheduleStartDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesVisibleByTenancy.servicePeriodStartDate", "Amber DATETIME legacy." )
                        .AddFilter( "dbo.vw_VehicleSharesVisibleByTenancy.startOfDayTime", "Amber DATETIME legacy." )
                        .AddFilter( "INFORMATION_SCHEMA.ROUTINES.CREATED", "Amber DATETIME legacy." )
                        .AddFilter( "INFORMATION_SCHEMA.ROUTINES.LAST_ALTERED", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_BusinessEvent.eventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_BusinessEventLocations.EventDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_VehicleDayMovements.vehicleDate", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_VehicleDaySummary.vehicleDate", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_VehicleLocationGeofenceHistory.arrivedtime", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_VehicleLocationGeofenceHistory.departuretime", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_VehicleLocationHistory.ArrivedTime", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_VehicleLocationHistory.DepartureTime", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_VehicleSharesCurrentlyVisibleByTenancy_withTenantName.AppliesFromInUtc", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_VehicleSharesCurrentlyVisibleByTenancy_withTenantName.AppliesToInUTC", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_VehicleSharesCurrentlyVisibleByTenancy_withTenantName.createdDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_VehicleSharesCurrentlyVisibleByTenancy_withTenantName.lastUpdatedDateTime", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_VehicleSharesCurrentlyVisibleByTenancy_withTenantName.SafetyInspectionScheduleStartDate", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_VehicleSharesCurrentlyVisibleByTenancy_withTenantName.servicePeriodStartDate", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_VehicleSharesCurrentlyVisibleByTenancy_withTenantName.startOfDayTime", "Amber DATETIME legacy." )
                        .AddFilter( "reporting.vw_VehicleState.lasteventtime", "Amber DATETIME legacy." )
                        .AddFilter( "tSQLt.Run_LastExecution.LoginTime", "Amber DATETIME legacy." )
                        .AddFilter( "tSQLt.TestResult.TestEndTime", "Amber DATETIME legacy." )
                        .AddFilter( "tSQLt.TestResult.TestStartTime", "Amber DATETIME legacy." ))

                .FilterTest<PrimaryKeyOnAllTablesTest>(
                    new TestFilter()
                        .AddFilter( "dbo.tbl_AGS_NightlyJobs", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_Archiving", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_BusinessEventLocations", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_ContextualSpeedingNotifications", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_Copying", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_EngineLoadBusinessEvents", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_GeneratorLoadBusinessEvents", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_MatrixInstanceCopying", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_MatrixInstanceDeleting", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_Notifications", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_OldBusinessEvents", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_Reports", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_RetrofitVehicleTransfer", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_SafetyInspectionBusinessEvents", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_TrackedEventCopying", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_TrackedEventDeleting", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_TrackedRawCopying", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLock_TrackedRawDeleting", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLockExcessiveTimeStoppedAtUnknownLocation", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AGSLockExcessiveWaitingTimeAtGeofence", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AuditActions", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AuditReportError", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AuditReportError_old", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_AuditReportFilter", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_BillingContractCampaignRegion", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_DashBoard_TotalVehiclesInCountry", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_DTCCode", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_DTCCodeText", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_EngineRatingMatrixType", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_EngineType", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_ETL_DataImportLog", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_ExternalVehicleKnownProvider", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_ExternalVehicleProvider_ISO_15143_3", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_MasterProfileImport", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_MDNRegionMap", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_PlannedInstall", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_PowerPack_ExternalGeneratorRunConditionHistory", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_PowerWall_Current", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_PowerWall_Daily", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_PowerWall_Delta", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_PowerWall_Latest", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_ReportType_Machine_Blocks", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_ReportVerticalMarketMap", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_ResetEvent", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_ResourceClaimsByUser", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_RoleIdentifierRole", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_RolePermission", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_SafetyInspection", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_SafetyInspectionSchedule", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_ServiceHistory_Generators", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_SubsidTenantLookup", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_System", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_TeaTrackedEventTempTableCopy", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_Tenant_old", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_TenantDTCCode", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_TrackingUnitCommandStatusUpdate", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_TrackingUnitLargeGenericData", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_TrackingUnitLog", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_TrackingUnitType", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_UserCommunication_Attachment", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_UserReportCriteriaDaysInWeek", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_UserReportCriteriaGroups", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_UserReportEmailAddress", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_Vehicle_Default_Driver_History", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_Vehicle_Driver_History", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_VehicleActiveDTC", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_VehicleMovementStatus", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_VehicleState_BatteryStateData", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_VehicleState_MotorData", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_VehicleTransmissionDutyCycleData", "Amber legacy for consistency." )
                        .AddFilter( "dbo.tbl_VINPattern", "Amber legacy for consistency." )
                        .AddFilter( "tSQLt.Private_AssertEqualsTableSchema_Actual", "Amber legacy for consistency." )
                        .AddFilter( "tSQLt.Private_AssertEqualsTableSchema_Expected", "Amber legacy for consistency." )
                        .AddFilter( "tSQLt.Private_ExpectException", "Amber legacy for consistency." )
                        .AddFilter( "tSQLt.Private_NullCellTable", "Amber legacy for consistency." )
                        .AddFilter( "tSQLt.Run_LastExecution", "Amber legacy for consistency." )
                        .AddFilter( "tSQLt.TestMessage", "Amber legacy for consistency." ))

            .RunTests();
        }
    }
}